### ISSUE TITLE
Error when i start main.py

### ISSUE THREAD

**Issue by 1581-netizen** [m4mallu/uniquify#9]
Traceback (most recent call last):
  File "/docker/uniquify/main.py", line 3, in <module>
    Bot().run()
  File "/docker/uniquify/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 54, in run
    run(self.start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/docker/uniquify/bot.py", line 38, in start
    self.USER, self.USER_ID = await User().start()
  File "/docker/uniquify/user.py", line 23, in start
    await super().start()
  File "/docker/uniquify/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/docker/uniquify/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/docker/uniquify/lib/python3.10/site-packages/pyrogram/client.py", line 677, in load_session
    await self.storage.open()
  File "/docker/uniquify/lib/python3.10/site-packages/pyrogram/storage/memory_storage.py", line 38, in open
    dc_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
struct.error: unpack requires a buffer of 267 bytes

**Comment by m4mallu** [comment]
Sorry, I won't give support to an edited repo.
